### ISSUE TITLE
在windows环境下，成功使用\lishu 命令

### ISSUE THREAD

**Issue by specialpointcentral** [Regulust/hithesis-alpha#1]
在windows环境下，成功使用\lishu 命令。

- 更改`hithesis.dtx`2409行
`\centerline{\haiti\textbf{哈尔滨工业大学教务处制}}`
改为
`\centerline{\lishu\textbf{哈尔滨工业大学教务处制}}`

- 再次执行[模板编译](https://github.com/dustincys/hithesis#%E6%A8%A1%E6%9D%BF%E7%9A%84%E7%BC%96%E8%AF%91%E6%96%B9%E6%B3%95)

- Over!

**Comment by Regulust** [comment]
👍
只是我手头暂时没有Windows，非Win系统下载安装了隶书字体后，用\lishu还是maketitle报错，暂时code里就还是没改\lishu了，TeX字体问题也真是头疼。

**Comment by specialpointcentral** [comment]
> 
> 
> 👍
> 只是我手头暂时没有Windows，非Win系统下载安装了隶书字体后，用\lishu还是maketitle报错，暂时code里就还是没改\lishu了，TeX字体问题也真是头疼。

确实是，写报告的时候再研究一下字体问题。

另外这里有个bug，图表的自动编号，遇到新的部分不会重新编号，而是顺位编号，如：
表1-1后就是表2-2了

**Comment by Regulust** [comment]
@specialpointcentral 😂，刚解决了图表自动编号的问题，默认的图表计数器是跟随chapter刷新重置的，现在kaiti/zhongqi改了跟随section刷新 `\numberwithin{figure}{section}`。
参考链接：https://blog.csdn.net/aldielshala/article/details/88582076

**Comment by specialpointcentral** [comment]
这个问题今日尝试了一下，在ubuntu下解决了。Mac也可以尝试。
## ubuntu解决方案
1. 首先安装对应字体，可以在windows上弄下来，也可以[下载](https://github.com/eclipselu/zjuthesis-mphil/files/1810427/youyan_lisu.zip)并安装。
2. 然后修改文件：`/usr/share/texlive/texmf-dist/tex/latex/ctex/fontset/ctex-fontset-fandol.def`
3. 修改内部的代码：
  - 在`\NewDocumentCommand \kaishu   { } { \CJKfamily { zhkai } }`后添加
  `\NewDocumentCommand \lishu    { } { \CJKfamily { zhli } }`
  - 在`\setCJKfamilyfont { zhkai } [ Extension = .otf ] { FandolKai-Regular }`后添加
  `\setCJKfamilyfont { zhli }   { LiSu }`
4. 编译就可以了

## Mac解决方案
可以参考 https://github.com/eclipselu/zjuthesis-mphil/issues/5#issue-305090691

**Comment by Regulust** [comment]
@specialpointcentral 太赞了，看到hithesis 更新v2.1.0 增加了一校三区支持，一直想找时间merge一下，一看你都做完了，最近找时间看一下就合并分之👍

**Comment by specialpointcentral** [comment]
主要是最近在做毕设，就给做了😂
